#!/usr/bin/python3
import git
  
repo = git.Repo(".")
origin = repo.remote(name='origin')
  
#existing_branch = repo.heads['main']
#existing_branch.checkout()
  
#repo.index.commit('Initial commit on new branch')
#print('Commited successfully')


origin.push()



