all:
	g++ -c speech_spanish.cpp -fmodules-ts -std=c++20
	g++ -c speech_english.cpp -fmodules-ts -std=c++20
	g++ -c speech.cpp -fmodules-ts -std=c++20
	g++ main.cpp *.o -fmodules-ts -std=c++20 -x c++-system-header iostream -x c++-system-header cstdlib



